language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
services:
- redis-server
branches:
  only:
  - master    
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
script:
- npm test
- npm run test-integrations
- npm run test-phantomjs
- npm run test-firefox
